name: Rulare Java HPC QFLPN
on: [push, workflow_dispatch]

jobs:
  run-java:
    runs-on: ubuntu-latest
    steps:
      - name: Descarca codul
        uses: actions/checkout@v4

      - name: Configureaza Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compileaza si Ruleaza algoritmul CSR
        run: |
          javac Main.java
          java Main
          
